<nav class="navbar custom-navbar">
	<ul class="left-ul list-group list-group-horizontal flex-row">
		<li class="list-item"><a href="javascript:;">Capabilities</a></li>
		<li class="list-item"><a href="javascript:;">Industries</a></li>
		<li class="list-item"><a href="javascript:;">Resources</a></li>
		<li class="list-item"><a href="javascript:;">Supplies</a></li>
		<li class="list-item"><a href="javascript:;">Become a Partner</a></li>
	</ul>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="test" name="test"></ul>
		<!-- <div class="d-flex ml-auto">
			<form class="form-inline my-2 my-lg-0">
				<div class="search position-relative">
					<input class="form-control mr-sm-2 position-relative" type="search" placeholder="Search" aria-label="Search">
					<span class="position-absolute"><i class="fas fa-search"></i></span>
				</div>
			</form>
			<ul class="navbar-nav right-ul d-flex align-items-center">
				<li class="nav-item active">
					<a class="nav-link" href="javascript:;"><i class="fas fa-user"></i> Login </a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="javascript:;">Cart <i class="fas fa-cart-plus"></i></a>
				</li>
			</ul>
		</div> -->
	</div>
</nav>